### ISSUE TITLE
All-in-one enhancement

### ISSUE THREAD

**Issue by bnordgren** [jaymzx/RPi-WD-Packet-Interface#2]
I think it may be valuable to have a single USB cable connect you to: 
1. A sound card connected directly to a radio interface (on PCB)
2. A GPS
3. An extra USB port (to replace the one consumed by this peripheral)

This may go a ways to reduce the cabling, and/or make it possible to use everything from a Raspberry Pi Zero to a router running OpenWRT to a desktop computer.

**Comment by kg5ebi** [comment]
A USB 1:7 hub controller IC costs only $1 to add. A CM108 IC is about the same cost. I think an improvement would be to have the LED contacts coming off the board as female headers because the LED's likely would be routed elsewhere in the project and the board not always visible.

JayMZX what size of donation would it take to make these few mods a possibility?

**Comment by bnordgren** [comment]
@kg5ebi I'm adopting some of this as a part of a larger APRS project for 2017. [1]  I think I'm going to leave the GPS as an external USB peripheral, but I like your suggestion as to sound card chip and USB hub chip. It also occurs to me that powerpole connectors on this device could be what ultimately provides power to the Pi via USB. If you'd like to participate or track progress, my fork of this repository may be the right place. I've started to triage some of the improvements into discrete issues. Your comments, suggestions, and/or efforts are welcome.

Closing this issue to let @jaymzx move on. ;) 

73, AF7RQ

[1] http://www.mineral-ares.org/blog/wifi-hotspot-aprs-web-mapper
